### ISSUE TITLE
Esc menu blank

### ISSUE THREAD

**Issue by OfficerHonk** [Foohy/jazztronauts#41] opened 2018-08-06 05:53 UTC
Upon attempting to open my esc menu, it will just be a blank white screen. I am able to access console, but a completely blank white esc menu doesn't feel like an intended feature. I am only running the Jazztronaut mods to stop any influence on the game, if that is any help.

(Update) Disconnecting VIA console made the start menu blank and white as well. Restarting gmod fixes said error.

**Comment by mets11rap** [comment] 2018-08-07 13:05
This happens to me sometimes too. The screen is completely white, but you can still interact with it. I was unable to determine the cause.

**Comment by mets11rap** [comment] 2019-05-19 04:29
This issue should be closed.

**Comment by Foohy** [comment] 2023-05-21 22:45
Weird, closing for now as no repro because I don't think I've ever seen this/might be a gmod bug itself.

**Closed by Foohy** 2023-05-21 22:45 UTC
