### ISSUE TITLE
Can't load the dialogue apparently 

### ISSUE THREAD

**Issue by JoltDerg** [Foohy/jazztronauts#32] opened 2018-08-04 19:11 UTC
it just gives me a big ol textbox that says "nil*
and nothing happens
+ this error
[ERROR] addons/jazztronauts-master/gamemodes/jazztronauts/gamemode/ui/dialog/cl_dialog.lua:311: attempt to call upvalue 'iter' (a nil value)
  1. nodeiter - addons/jazztronauts-master/gamemodes/jazztronauts/gamemode/ui/dialog/cl_dialog.lua:311
   2. nop - addons/jazztronauts-master/gamemodes/jazztronauts/gamemode/ui/dialog/cl_dialog.lua:123
    3. State - addons/jazztronauts-master/gamemodes/jazztronauts/gamemode/ui/dialog/cl_dialog.lua:190
     4. nop - addons/jazztronauts-master/gamemodes/jazztronauts/gamemode/ui/dialog/cl_dialog.lua:92
      5. Update - addons/jazztronauts-master/gamemodes/jazztronauts/gamemode/ui/dialog/cl_dialog.lua:299
       6. v - addons/jazztronauts-master/gamemodes/jazztronauts/gamemode/ui/cl_init.lua:25
        7. unknown - lua/includes/modules/hook.lua:84
seems to be an issue with not having the proper scripts, idunno

**Comment by Foohy** [comment] 2018-08-04 19:39
Is this the github version or workshop version? I've been seeing this a lot and it _seems_ like it's a conflicting addon, but I don't know which one or if its just a bad download.

**Comment by JoltDerg** [comment] 2018-08-04 20:54
I'm hosting and this happens in both versions

**Comment by tatokis** [comment] 2018-08-08 13:53
It is definitely an addon conflict.
I had to unsubscribe from everything and wipe my addons folder to get it to work.

After deleting everything and only installing jazztronauts and a bunch of player models, the mode started showing up and everything worked as it should when connecting to a server.

**Comment by Foohy** [comment] 2018-08-11 17:14
If someone could help track down which addon it is (or at least provide a list of addons where it did happen), that'd help a lot.

I do know there's also a separate issue where the scripts just won't mount at all, and it causes the same issue.

**Comment by tatokis** [comment] 2018-08-11 17:43
Here's a (long) list of all the addons I had before I cleaned the addons folder, and excluding any of the currently installed addons that are confirmed to not conflict.

Some are deprecated, and some don't even exist in the workshop any more.
https://vps.tasossah.com/bugs/gmodaddonlist.txt

I'll try to update this once I start reinstalling some of them again.

**Comment by Foohy** [comment] 2023-05-21 22:48
This should be fixed, dialog loading has been significantly reworked since then. This was probably back in the days where dialog was in a separate addon than the other content. Also, dialog is now loaded from the server if it has custom scripts.

**Closed by Foohy** 2023-05-21 22:48 UTC
